name: CD

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Push code to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY}}
          REMOTE_HOST: ${{ secrets.SSH_HOST}}
          REMOTE_USER: ${{ secrets.SSH_USER}}
          REMOTE_PORT: 22 
          SOURCE: ./  
          TARGET: /var/www/apps/  
          SCRIPT_AFTER: |
            cd /var/www/apps/
            npm install
            npm run migrate up