name: CD

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: push-to-ec2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.SSH_HOST}}
          REMOTE_PORT: 22
          REMOTE_USER: ${{ secrets.SSH_USER}}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY}}
          TARGET: "/var/www/apps/"