name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
          POSTGRES_DB: ${{ secrets.PGDATABASE }}
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          PGHOST: localhost
          PGHOST_TEST: localhost
          PGUSER: ${{ secrets.PGUSER}}
          PGUSER_TEST: ${{ secrets.PGUSER}}
          PGPASSWORD: ${{ secrets.PGPASSWORD}}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD}}
          PGDATABASE: ${{ secrets.PGDATABASE}}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE}}
          PGPORT: 5432
          PGPORT_TEST: 5432
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
    
